### ISSUE TITLE
My *_SUCCEEDED and *_FAILED mutation functions are not triggered.

### ISSUE THREAD

**Issue by shinja** [MatteoGabriele/vuex-promise-middleware#1]
Env:
    "vue": "^2.2.6",
    "vuex": "^2.3.1",

The store.hotUpdate() seems replace  *_SUCCEEDED and *FAILED mutation functions.

**Comment by MatteoGabriele** [comment]
Hi @shinja, could you please post what did you wrote? a piece of code,  an examples

thanks! :)

**Comment by shinja** [comment]
Hi @MatteoGabriele 
I was doing a todo app for practicing.
I originally applied the vuex-promise-middleware in Vuex plugins, however, I didn't receive *_SUCCEEDED commit after the promise resolved.

Here is my code.
https://github.com/shinja/vue-todo/blob/master/src/store/index.js
https://github.com/shinja/vue-todo/blob/master/src/store/mutations.js

In the last, I copy the middleware function in my project, and remove the hotUpdate function, it's working. Maybe I missed something, if you can give me some advises, it would be great. Thank you.

**Comment by MatteoGabriele** [comment]
You are not using the npm package or do you? I see some code here and there that looks like the code I wrote with some missing parts.

**Comment by shinja** [comment]
Hi, @MatteoGabriele 

Originally, I was using the middleware, but in the last, I copied the vuexPromiseMiddleware function in todo project for testing.
I rollbacked the todo project and applying the middleware package. 
Here is my code
https://github.com/shinja/vue-todo/blob/master/src/store/index.js

Thanks for your help.

**Comment by MatteoGabriele** [comment]
so what's the issue again? what can i do to have the same error you have?

**Comment by shinja** [comment]
Sorry, I think I didn't explain the issue very clearly, please forgive my bad English.

I have a fetchPending property in state.js to check if the fetching is in progress.
**state.js**
```
{
...
fetchPending: false
}
```

I use a simple setTimeout function as the asynchronous action, and pass a Promise object as the payload.
**actions.js**
```
export const addTodo = ({ commit }, payload) => {
  commit(types.ADD_TODO, new Promise((resolve) => {
    setTimeout(() => {
      resolve(payload);
    }, 1000);
  }));
};
```

**mutations.js**
```
const pending = (s) => {
  const state = s;
  state.fetchPending = true;
  state.fetchError = null;
};

const done = (s, err) => {
  const state = s;
  state.fetchPending = false;
  state.fetchError = err;
};

export default {

  [types.ADD_TODO]: pending,
...
  [`${types.ADD_TODO}_SUCCEEDED`]: (s, payload) => {
    const state = s;
    done(state, null);
    state.todos.push({
      content: payload,
      done: false,
    });
  },
```

I got the first ADD_TODO commit after the `addTodo` action is executed, so the `pending()` function is invoked and the `fetchPending` state is set as true. But the [`${types.ADD_TODO}_SUCCEEDED`] mutation function is not invoked after the promise is resolved, so the `fetchPending` is still be true.

If you don't mind, could you please clone my todo project and run it? I think it maybe will much clear about my problem. Thank you.

Again, apology for my bad explanation.

**Comment by MatteoGabriele** [comment]
Thanks a lot to share you repository but I really have problems using that setup: the linter is killing me 😄  no offense! 

I made a todo thing for you so you can check, because it is working.
https://github.com/MatteoGabriele/todo

I seriously have problems just typing with that linter like that.

store is [here](https://github.com/MatteoGabriele/todo/blob/master/src/core/vuex.js)
todo vuex module is [here](https://github.com/MatteoGabriele/todo/blob/master/src/app/data/store/todo/index.js) 
the todo app logic itself is [here](https://github.com/MatteoGabriele/todo/blob/master/src/app/page/home/home.js)
this todo app template is [here](https://github.com/MatteoGabriele/todo/blob/master/src/app/page/home/home.vue)

let me know if you can find everything and look at it!
I suggest you to create a new application from scratch and go slowly.

**Comment by MatteoGabriele** [comment]
this is the app

![screen recording 2017-04-28 at 07 10 pm](https://cloud.githubusercontent.com/assets/5337152/25539209/652987a2-2c46-11e7-8cc9-956ac4c59f34.gif)

**Comment by shinja** [comment]
Hi @MatteoGabriele 

Thank you provide me an example. I run it, it's working. There might be something wrong in my project. Thanks for your help, really appreciate. I'm still trying to figure out where the problem is, but really appreciate your helping.

**Comment by MatteoGabriele** [comment]
@shinja I would suggest to create a really bare bones project with vue, vuex and the plugin and try to create the same todo, if works and it actually does, then you can figure out what's the issue in your scaffold.

Sorry I couldn't help more then that, but was more the code I was not understanding than the rest.

Let me know if you succeed on that and thanks for your feedback!

**Comment by shinja** [comment]
Hi @MatteoGabriele 

Thank your suggestion. I create a new project with vue-cli, and only install vue, vuex and the middleware plugin. I think I got something.

It's working if I use vuex modules while creating the Vuex.Store object.
```
export default new Vuex.Store({
  modules: {
    todo: TodoModule
  },
  strict: debug,
  plugins
})
```
![working](https://cloud.githubusercontent.com/assets/1415378/25555602/8cbfb570-2d1d-11e7-97eb-dc7fd6328b87.gif)


But it's not working if I spread the `TodoModule` into Vuex.Store
```
export default new Vuex.Store({
  ...TodoModule, // not working
  strict: debug,
  plugins
})
```
![not_working](https://cloud.githubusercontent.com/assets/1415378/25555604/95e68a34-2d1d-11e7-91b9-459d82455da1.gif)

I put the simple todo project in [here](https://github.com/shinja/simple-todo-vue-vuex), If you want to try.

The Vuex Store is [here](https://github.com/shinja/simple-todo-vue-vuex/blob/master/src/store/index.js)
The TodoModule is [here](https://github.com/shinja/simple-todo-vue-vuex/blob/master/src/store/todoModule.js)
The Todo view component is [here](https://github.com/shinja/simple-todo-vue-vuex/blob/master/src/components/Todo.vue).

Honestly, I have no idea why this happened, but I got a way to make it working. Thank your help and suggestion, it's really helpful. :)

**Comment by MatteoGabriele** [comment]
@shinja I did some testes and researches and apparently the vuex store `hotUpdate` method it's only working when combined with modules, because it's a sort of hot module replacement.

So you need to use them like so or won't work. I always use modules so that's why I never saw this error and I use this module pretty much in all my projects.

Good to know, I will add it on the README file

Thanks for your feedback again!
